executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: generator
    json_schema:
      contentMediaType: oomol/var
    kind: generator
    nullable: false
  - handle: name
    json_schema:
      type: string
      minLength: 1
    value:
    nullable: true
  - handle: kind
    json_schema:
      enum:
        - layout
        - span
      ui:options:
        labels:
          - Layout
          - Span
    value: layout
outputs_def:
  - handle: file_path
    json_schema:
      type: string
      ui:widget: file
title: Draw PDF file
ui:
  default_width: 350
